config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.create(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @reviews = Review.find(params[:id])
    @reviews.destroy
    redirect_to restaurant_path(@reviews.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
<%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number%>
    <%= f.input :category%>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>🐙Restaurants🥔</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %></li>
    <%= link_to 'Show', restaurant %>
    <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
    <%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</ul>

<br>

<%= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-primary' %>

app/views/restaurants/new.html.erb
<h1>🥢Add a new Restaurant🥡</h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1>🐽<%= @restaurant.name %>🐽</h1>
<h3>👩🏻‍🍳<%= @restaurant.category %></h2>
<h3>📍<%= @restaurant.address %></h2>
<h3>☎️<%= @restaurant.phone_number %></h2>
<br>
<br>
<h3>Reviews</h3>
<% @restaurant.reviews.each do |review| %>
<p><%= review.content %> Rating: <%= review.rating %>
<%= link_to "Delete", review_path(review), method: :delete, data: {confirm: "Are you sure?"} %></p>
<% end %>

<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/reviews/new.html.erb
<h1>Your review🍤</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, placeholder: "Leave a review" %>
  <%= f.input :rating, placeholder: "add a rating (1-5)" %>
  <br>
  <%= f.submit 'add', class: 'btn btn-primary' %>
<% end %>
<br>
<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>